#**We are using colab.google.com to run models by using IRIS.CSV spread sheet data**
Upload iris.csv to Colab before using it

In [137]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

# Importing IRIS File

In [138]:
from sklearn.datasets import load_iris
dataframe = load_iris()

In [139]:
dataframe

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [140]:
dataset = pd.read_csv('iris.csv')
dataset

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [141]:
dataset.describe(include='all')  # include all columns

sepal.length  sepal.width  petal.length  petal.width variety
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  Setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [142]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [143]:
X = dataset.iloc[:, :-1].values

In [144]:
y = dataset.iloc[:, -1].values

In [145]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [146]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [147]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Apply Logistic Regression

In [148]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [149]:
model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [150]:
y_predict = model.predict(X_test)

In [151]:
y_predict

array([0, 0, 2, 2, 1, 1, 1, 1, 2, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1,
       0, 0, 2, 2, 2, 2, 2, 2])

In [152]:
y_test

array([0, 0, 2, 2, 1, 1, 1, 2, 2, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1,
       0, 0, 2, 2, 2, 2, 2, 1])

In [153]:
from sklearn.metrics  import confusion_matrix
cm = confusion_matrix(y_test, y_predict)
print(cm)
print("Accurancy = ", 30/30)

[[ 9  0  0]
 [ 0  5  1]
 [ 0  1 14]]
Accurancy =  1.0


# Apply KN-Neighbor

In [154]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
model.fit(X_train, y_train)

KNeighborsClassifier()

In [155]:
model.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [156]:
y_predict = model.predict(X_test)
y_predict

array([0, 0, 2, 2, 1, 1, 1, 1, 2, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1,
       0, 0, 2, 2, 2, 2, 2, 2])

In [157]:
cm = confusion_matrix(y_predict, y_test)
print(cm)
print('Accurancy = ', 29/30)

[[ 9  0  0]
 [ 0  5  1]
 [ 0  1 14]]
Accurancy =  0.9666666666666667


# Apply Naive Bayes

In [158]:
from sklearn.naive_bayes import GaussianNB
model_nb = GaussianNB()
model_nb.fit(X_train, y_train)

GaussianNB()

In [159]:
model.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [160]:
y_predit = model_nb.predict(X_test)
y_predit

array([0, 0, 2, 2, 1, 1, 1, 1, 2, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1,
       0, 0, 2, 2, 2, 2, 2, 2])

In [161]:
cm = confusion_matrix(y_predit, y_test)
print(cm)
print('Accurancy', 29/30)

[[ 9  0  0]
 [ 0  5  1]
 [ 0  1 14]]
Accurancy 0.9666666666666667


# Apply Support Vector Machine With Following Kernels
1. Sigmoid Kernel

In [162]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [163]:
classifier_svm_sigmoid.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'sigmoid',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [164]:
y_predit = classifier_svm_sigmoid.predict(X_test)
y_predit

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [165]:
cm = confusion_matrix(y_test, y_predit)
print('CM',cm)
print('Accuracy = ', 8/30)

CM [[ 0  9  0]
 [ 0  6  0]
 [ 0 15  0]]
Accuracy =  0.26666666666666666


1. Linear Kernel

In [166]:
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(X_train, y_train)

SVC(kernel='linear')

In [181]:
classifier_svm_linear.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'linear',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [167]:
y_predict = classifier_svm_linear.predict(X_test)

In [168]:
cm = confusion_matrix(y_test, y_predict)
print(cm)
print('Accurancy',28/30)

[[ 9  0  0]
 [ 0  5  1]
 [ 0  0 15]]
Accurancy 0.9333333333333333


3. RBF Kernel

In [169]:
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(X_train, y_train)

SVC()

In [170]:
y_predict = classifier_svm_rbf.predict(X_test)
y_predit

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [171]:
cm = confusion_matrix(y_test, y_predict)
print(cm)
print('Accurancy = ', 29/30)

[[ 9  0  0]
 [ 0  5  1]
 [ 0  1 14]]
Accurancy =  0.9666666666666667


4. Poly Kernel

In [172]:
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel='poly')
classifier_svm_poly.fit(X_train, y_train)

SVC(kernel='poly')

In [173]:
y_predict = classifier_svm_poly.predict(X_test)
y_predit

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [174]:
cm = confusion_matrix(y_test, y_predict)
print(cm)
print('Accurancy = ', 29/30)

[[ 9  0  0]
 [ 0  5  1]
 [ 0  1 14]]
Accurancy =  0.9666666666666667


# Decision Tree Classifier

In [175]:
from sklearn.tree import DecisionTreeClassifier
classifier_dtree = DecisionTreeClassifier(criterion = 'entropy')
classifier_dtree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [182]:
classifier_dtree.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [176]:
y_predict = classifier_dtree.predict(X_test)
y_predit

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [177]:
cm = confusion_matrix(y_test, y_predict)
print(cm)
print('Accurancy = ', 28/30)

[[ 9  0  0]
 [ 0  5  1]
 [ 0  1 14]]
Accurancy =  0.9333333333333333


# Random Forest Classifier

In [178]:
from sklearn.ensemble import RandomForestClassifier
classifier_forest = RandomForestClassifier(n_estimators=3, criterion = 'entropy')
classifier_forest.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [179]:
y_predict = classifier_forest.predict(X_test)
y_predit

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [180]:
cm = confusion_matrix(y_test, y_predict)
print(cm)
print('Accurancy = ', 29/30)

[[ 9  0  0]
 [ 0  5  1]
 [ 0  1 14]]
Accurancy =  0.9666666666666667
